### ISSUE TITLE
Missing Photocell files in v2.2.0

### ISSUE THREAD

**Issue by ajschwieterman** [robertgallup/arduino-BobaBlox#2]
It looks like the Photocell files from this library were deleted.  Just curious if that was intentional, and if so, why these files were removed.

**Comment by robertgallup** [comment]
Good question! It had me scratching my head for awhile! :-)

So, first I checked the Photocell example and found it compiled without the Photocell files. Then I remembered what I'd done. I realized the Photocell class was exactly the same as the Knob class (potentiometer). The photocell circuit requires another resistor to create a voltage divider just like a potentiometer. So, rather than duplicate code, I aliased the two classes so that Photocell just creates a Knob class with a different name. You can see this alias in the BobaBlox.h file.

Let me know if this answers your question.

**Comment by ajschwieterman** [comment]
Yes, this answers my question!  Thank you!

**Comment by robertgallup** [comment]
Excellent! Let me know if anything else comes up.
